    source "https://rubygems.org"

    gem 'test-unit', :group => [:development, :test]
    gem 'gauge-ruby', '~>0.5.2', :github => 'getgauge/gauge-ruby', :branch => 'master', :group => [:development, :test]
