    source "https://rubygems.org"

    gem 'test-unit', :group => [:development, :test]
    if ENV['LOCAL_RUBY_PLUGIN_PATH'].nil?
        gem 'gauge-ruby', '>= 0.5.3', :github => 'getgauge/gauge-ruby', :branch => ENV['RUBY_PLUGIN_BRANCH'] || 'master', :group => [:development, :test]
    else
        gem 'gauge-ruby', '>= 0.5.3', :path => ENV['LOCAL_RUBY_PLUGIN_PATH'], :group => [:development, :test]
    end

    if ENV['RUBY_PLUGIN_GRPC_SOURCE_BRANCH']
        gem 'grpc', :github => 'grpc/grpc', :branch => ENV['RUBY_PLUGIN_GRPC_SOURCE_BRANCH'], :submodules => true, :group => [:development, :test]
    end
